### ISSUE TITLE
Bottom blank space on latest iOS?

### ISSUE THREAD

**Issue by htorbov** [apache/cordova-plugin-wkwebview-engine#127]
I'm using the latest Cordova with this awesome plugin, latest Xcode and iOS as well, but I'm having troubles with a bottom blank space.

---

**Screenshot:**
![test](https://user-images.githubusercontent.com/1743266/70730025-f1b1dd00-1d0c-11ea-9e41-c2f02b497880.jpg)

---

**config.xml**
```xml
<preference name="webviewbounce" value="false" />
<preference name="UIWebViewBounce" value="false" />
<platform name="ios">
  <feature name="CDVWKWebViewEngine">
    <param name="ios-package" value="CDVWKWebViewEngine" />
  </feature>
  <preference name="CordovaWebViewEngine" value="CDVWKWebViewEngine" />
  <preference name="AllowBackForwardNavigationGestures" value="true" />
</platform>
```

---

**index.html:**
```html
<meta name="viewport" content="viewport-fit=cover, width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no" />
<meta name="format-detection" content="telephone=no" />
<meta name="msapplication-tap-highlight" content="no" />
<meta name="apple-mobile-web-app-capable" content="yes" />
<meta name="apple-mobile-web-app-status-bar-style" content="black" />
```

---

**styles.css:**
```css
html {
  width: 100%;
  height: 100%;
  text-size-adjust: 100%;
  visibility: inherit;
}

body {
  -moz-osx-font-smoothing: grayscale;
  -webkit-font-smoothing: antialiased;
  position: fixed;
  width: 100%;
  max-width: 100%;
  height: 100%;
  max-height: 100%;
  text-rendering: optimizeLegibility;
  overflow: hidden;
  touch-action: manipulation;
  -webkit-user-drag: none;
  -ms-content-zooming: none;
  word-wrap: break-word;
  overscroll-behavior-y: none;
  text-size-adjust: none;
  margin: 0;
  padding: 0;
}

main {
  left: 0;
  right: 0;
  top: 0;
  bottom: 0;
  display: flex;
  position: absolute;
  flex-direction: column;
  justify-content: space-between;
  contain: layout size style;
  overflow: hidden;
  z-index: 0;
}

header {
  display: block;
  position: relative;
  -ms-flex-order: -1;
  order: -1;
  width: 100%;
  z-index: 10;
}

section {
  overflow: auto;
  -webkit-overflow-scrolling: touch;
  display: block;
  position: relative;
  width: 100%;
  height: 100%;
  contain: size style;
  flex: 1 1 0%;
  margin: 0px !important;
  padding: 0px !important;
}

footer {
  display: block;
  position: relative;
  -ms-flex-order: 1;
  order: 1;
  width: 100%;
  z-index: 10;
}
```
